---
openai_access_token: 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
selected_file: "/home/b08x/Workspace/obsidian/notes/scriberPad.md"
last_selected_file: "/home/b08x/Workspace/obsidian/notes/scriberPad.md"
input_source: jack
jack_port: system:capture_1
